source 'https://rubygems.org'

gem "jekyll", "~> 4.3.4" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

#gem "just-the-docs", "0.6.2" # pinned to the current release
gem "just-the-docs"        , ">= 0.10.0" # always download the latest release
